-- Create patients table
create table if not exists public.patients (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  time text not null,
  type text not null,
  complaint text,
  keywords text[],
  status text check (status in ('pending', 'completed')) default 'pending'
);

-- Enable RLS
alter table public.patients enable row level security;

-- Policy: Allow read/update access to everyone (for demo simplicity)
-- In production, this should be restricted to authenticated staff
create policy "Enable read access for all users" on public.patients for select using (true);
create policy "Enable update for all users" on public.patients for update using (true);


